# Generated by Django 4.2.23 on 2025-07-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Formato',
                'verbose_name_plural': 'Formatos',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('synopsis', models.TextField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('classification', models.CharField(choices=[('TE', 'Todo espectador'), ('7+', 'Mayores de 7 años'), ('14+', 'Mayores de 14 años'), ('18+', 'Mayores de 18 años')], max_length=10)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movies/posters/')),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=200, null=True)),
                ('main_cast', models.TextField(blank=True, help_text='Lista separada por comas o JSON con actores.', null=True)),
                ('production_company', models.CharField(blank=True, max_length=200, null=True)),
                ('original_language', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_audience', models.PositiveIntegerField(blank=True, help_text='Número estimado de asistentes.', null=True)),
                ('is_scheduled', models.BooleanField(default=True, help_text='Marca si será exhibida próximamente.')),
                ('release_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formats', models.ManyToManyField(related_name='movies', to='cinema.format')),
                ('genres', models.ManyToManyField(related_name='movies', to='cinema.genre')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'ordering': ['-release_date'],
            },
        ),
    ]
